// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: sys_menu.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSysMenuReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MenuName    string `protobuf:"bytes,1,opt,name=menuName,proto3" json:"menuName,omitempty"`        // menu名称
	Desc        string `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`                // 描述
	Route       string `protobuf:"bytes,3,opt,name=route,proto3" json:"route,omitempty"`              // 菜单路由
	State       uint32 `protobuf:"varint,4,opt,name=state,proto3" json:"state,omitempty"`             // 1显示,2否
	Pid         uint64 `protobuf:"varint,5,opt,name=pid,proto3" json:"pid,omitempty"`                 // 父id
	Pname       string `protobuf:"bytes,6,opt,name=pname,proto3" json:"pname,omitempty"`              // 父路由名称
	SortOrder   int32  `protobuf:"varint,7,opt,name=sortOrder,proto3" json:"sortOrder,omitempty"`     // 排序
	BackendType int32  `protobuf:"varint,8,opt,name=backendType,proto3" json:"backendType,omitempty"` // 1总后台，2运营后台
}

func (x *CreateSysMenuReq) Reset() {
	*x = CreateSysMenuReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_menu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSysMenuReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSysMenuReq) ProtoMessage() {}

func (x *CreateSysMenuReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_menu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSysMenuReq.ProtoReflect.Descriptor instead.
func (*CreateSysMenuReq) Descriptor() ([]byte, []int) {
	return file_sys_menu_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSysMenuReq) GetMenuName() string {
	if x != nil {
		return x.MenuName
	}
	return ""
}

func (x *CreateSysMenuReq) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *CreateSysMenuReq) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *CreateSysMenuReq) GetState() uint32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *CreateSysMenuReq) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *CreateSysMenuReq) GetPname() string {
	if x != nil {
		return x.Pname
	}
	return ""
}

func (x *CreateSysMenuReq) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *CreateSysMenuReq) GetBackendType() int32 {
	if x != nil {
		return x.BackendType
	}
	return 0
}

type CreateSysMenuRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ulid string `protobuf:"bytes,1,opt,name=ulid,proto3" json:"ulid,omitempty"`
}

func (x *CreateSysMenuRsp) Reset() {
	*x = CreateSysMenuRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_menu_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSysMenuRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSysMenuRsp) ProtoMessage() {}

func (x *CreateSysMenuRsp) ProtoReflect() protoreflect.Message {
	mi := &file_sys_menu_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSysMenuRsp.ProtoReflect.Descriptor instead.
func (*CreateSysMenuRsp) Descriptor() ([]byte, []int) {
	return file_sys_menu_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSysMenuRsp) GetUlid() string {
	if x != nil {
		return x.Ulid
	}
	return ""
}

type DeleteSysMenuReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ulid string `protobuf:"bytes,1,opt,name=ulid,proto3" json:"ulid,omitempty"`
}

func (x *DeleteSysMenuReq) Reset() {
	*x = DeleteSysMenuReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_menu_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSysMenuReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSysMenuReq) ProtoMessage() {}

func (x *DeleteSysMenuReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_menu_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSysMenuReq.ProtoReflect.Descriptor instead.
func (*DeleteSysMenuReq) Descriptor() ([]byte, []int) {
	return file_sys_menu_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteSysMenuReq) GetUlid() string {
	if x != nil {
		return x.Ulid
	}
	return ""
}

type UpdateSysMenuReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ulid        string `protobuf:"bytes,1,opt,name=ulid,proto3" json:"ulid,omitempty"`                // ID
	MenuName    string `protobuf:"bytes,2,opt,name=menuName,proto3" json:"menuName,omitempty"`        // menu名称
	Desc        string `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`                // 描述
	Route       string `protobuf:"bytes,4,opt,name=route,proto3" json:"route,omitempty"`              // 菜单路由
	State       uint32 `protobuf:"varint,5,opt,name=state,proto3" json:"state,omitempty"`             // 1显示,2否
	Pid         uint64 `protobuf:"varint,6,opt,name=pid,proto3" json:"pid,omitempty"`                 // 父id
	Pname       string `protobuf:"bytes,7,opt,name=pname,proto3" json:"pname,omitempty"`              // 父路由名称
	SortOrder   int32  `protobuf:"varint,8,opt,name=sortOrder,proto3" json:"sortOrder,omitempty"`     // 排序
	BackendType int32  `protobuf:"varint,9,opt,name=backendType,proto3" json:"backendType,omitempty"` // 1总后台，2运营后台
}

func (x *UpdateSysMenuReq) Reset() {
	*x = UpdateSysMenuReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_menu_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSysMenuReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSysMenuReq) ProtoMessage() {}

func (x *UpdateSysMenuReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_menu_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSysMenuReq.ProtoReflect.Descriptor instead.
func (*UpdateSysMenuReq) Descriptor() ([]byte, []int) {
	return file_sys_menu_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateSysMenuReq) GetUlid() string {
	if x != nil {
		return x.Ulid
	}
	return ""
}

func (x *UpdateSysMenuReq) GetMenuName() string {
	if x != nil {
		return x.MenuName
	}
	return ""
}

func (x *UpdateSysMenuReq) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *UpdateSysMenuReq) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *UpdateSysMenuReq) GetState() uint32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *UpdateSysMenuReq) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *UpdateSysMenuReq) GetPname() string {
	if x != nil {
		return x.Pname
	}
	return ""
}

func (x *UpdateSysMenuReq) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *UpdateSysMenuReq) GetBackendType() int32 {
	if x != nil {
		return x.BackendType
	}
	return 0
}

type FindSysMenuByIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ulid string `protobuf:"bytes,1,opt,name=ulid,proto3" json:"ulid,omitempty"`
}

func (x *FindSysMenuByIdReq) Reset() {
	*x = FindSysMenuByIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_menu_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindSysMenuByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSysMenuByIdReq) ProtoMessage() {}

func (x *FindSysMenuByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_menu_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSysMenuByIdReq.ProtoReflect.Descriptor instead.
func (*FindSysMenuByIdReq) Descriptor() ([]byte, []int) {
	return file_sys_menu_proto_rawDescGZIP(), []int{4}
}

func (x *FindSysMenuByIdReq) GetUlid() string {
	if x != nil {
		return x.Ulid
	}
	return ""
}

type FindSysMenuRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ulid        string `protobuf:"bytes,1,opt,name=ulid,proto3" json:"ulid,omitempty"`                 // ID
	CreatedBy   string `protobuf:"bytes,4,opt,name=createdBy,proto3" json:"createdBy,omitempty"`       // 创建者
	DeletedBy   string `protobuf:"bytes,5,opt,name=deletedBy,proto3" json:"deletedBy,omitempty"`       // 删除者
	MenuName    string `protobuf:"bytes,6,opt,name=menuName,proto3" json:"menuName,omitempty"`         // menu名称
	Desc        string `protobuf:"bytes,7,opt,name=desc,proto3" json:"desc,omitempty"`                 // 描述
	Route       string `protobuf:"bytes,8,opt,name=route,proto3" json:"route,omitempty"`               // 菜单路由
	State       uint32 `protobuf:"varint,9,opt,name=state,proto3" json:"state,omitempty"`              // 1显示,2否
	Pid         uint64 `protobuf:"varint,10,opt,name=pid,proto3" json:"pid,omitempty"`                 // 父id
	Pname       string `protobuf:"bytes,11,opt,name=pname,proto3" json:"pname,omitempty"`              // 父路由名称
	SortOrder   int32  `protobuf:"varint,12,opt,name=sortOrder,proto3" json:"sortOrder,omitempty"`     // 排序
	BackendType int32  `protobuf:"varint,13,opt,name=backendType,proto3" json:"backendType,omitempty"` // 1总后台，2运营后台
}

func (x *FindSysMenuRsp) Reset() {
	*x = FindSysMenuRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_menu_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindSysMenuRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSysMenuRsp) ProtoMessage() {}

func (x *FindSysMenuRsp) ProtoReflect() protoreflect.Message {
	mi := &file_sys_menu_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSysMenuRsp.ProtoReflect.Descriptor instead.
func (*FindSysMenuRsp) Descriptor() ([]byte, []int) {
	return file_sys_menu_proto_rawDescGZIP(), []int{5}
}

func (x *FindSysMenuRsp) GetUlid() string {
	if x != nil {
		return x.Ulid
	}
	return ""
}

func (x *FindSysMenuRsp) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *FindSysMenuRsp) GetDeletedBy() string {
	if x != nil {
		return x.DeletedBy
	}
	return ""
}

func (x *FindSysMenuRsp) GetMenuName() string {
	if x != nil {
		return x.MenuName
	}
	return ""
}

func (x *FindSysMenuRsp) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *FindSysMenuRsp) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *FindSysMenuRsp) GetState() uint32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *FindSysMenuRsp) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *FindSysMenuRsp) GetPname() string {
	if x != nil {
		return x.Pname
	}
	return ""
}

func (x *FindSysMenuRsp) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *FindSysMenuRsp) GetBackendType() int32 {
	if x != nil {
		return x.BackendType
	}
	return 0
}

type FindSysMenuPageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query    []*Query  `protobuf:"bytes,1,rep,name=query,proto3" json:"query,omitempty"`
	PageData *PageData `protobuf:"bytes,2,opt,name=page_data,json=pageData,proto3" json:"page_data,omitempty"`
	SortData *SortData `protobuf:"bytes,3,opt,name=sort_data,json=sortData,proto3" json:"sort_data,omitempty"`
}

func (x *FindSysMenuPageReq) Reset() {
	*x = FindSysMenuPageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_menu_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindSysMenuPageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSysMenuPageReq) ProtoMessage() {}

func (x *FindSysMenuPageReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_menu_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSysMenuPageReq.ProtoReflect.Descriptor instead.
func (*FindSysMenuPageReq) Descriptor() ([]byte, []int) {
	return file_sys_menu_proto_rawDescGZIP(), []int{6}
}

func (x *FindSysMenuPageReq) GetQuery() []*Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *FindSysMenuPageReq) GetPageData() *PageData {
	if x != nil {
		return x.PageData
	}
	return nil
}

func (x *FindSysMenuPageReq) GetSortData() *SortData {
	if x != nil {
		return x.SortData
	}
	return nil
}

type FindSysMenuPageRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries  []*FindSysMenuRsp `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	PageData *PageData         `protobuf:"bytes,2,opt,name=page_data,json=pageData,proto3" json:"page_data,omitempty"`
}

func (x *FindSysMenuPageRsp) Reset() {
	*x = FindSysMenuPageRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_menu_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindSysMenuPageRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSysMenuPageRsp) ProtoMessage() {}

func (x *FindSysMenuPageRsp) ProtoReflect() protoreflect.Message {
	mi := &file_sys_menu_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSysMenuPageRsp.ProtoReflect.Descriptor instead.
func (*FindSysMenuPageRsp) Descriptor() ([]byte, []int) {
	return file_sys_menu_proto_rawDescGZIP(), []int{7}
}

func (x *FindSysMenuPageRsp) GetEntries() []*FindSysMenuRsp {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *FindSysMenuPageRsp) GetPageData() *PageData {
	if x != nil {
		return x.PageData
	}
	return nil
}

var File_sys_menu_proto protoreflect.FileDescriptor

var file_sys_menu_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x79, 0x73, 0x5f, 0x6d, 0x65, 0x6e, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd6,
	0x01, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x79, 0x73, 0x4d, 0x65, 0x6e, 0x75,
	0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x6e, 0x75, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x6e, 0x75, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x65, 0x73, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x70, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x6f, 0x72, 0x74, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x6f, 0x72, 0x74,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x62, 0x61, 0x63, 0x6b,
	0x65, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x22, 0x26, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x53, 0x79, 0x73, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x75,
	0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x6c, 0x69, 0x64, 0x22,
	0x26, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x79, 0x73, 0x4d, 0x65, 0x6e, 0x75,
	0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x6c, 0x69, 0x64, 0x22, 0xea, 0x01, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x53, 0x79, 0x73, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x6c, 0x69, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x6e, 0x75, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x6e, 0x75, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x65, 0x73, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63,
	0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x70, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x6f, 0x72, 0x74, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x6f, 0x72, 0x74, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x54, 0x79, 0x70, 0x65, 0x22, 0x28, 0x0a, 0x12, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x79, 0x73, 0x4d,
	0x65, 0x6e, 0x75, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6c,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x6c, 0x69, 0x64, 0x22, 0xa4,
	0x02, 0x0a, 0x0e, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x79, 0x73, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x73,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x75, 0x6c, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x42, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x42, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x42, 0x79,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x42,
	0x79, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x6e, 0x75, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x6e, 0x75, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73,
	0x63, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x70, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x70, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x6f, 0x72, 0x74, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x6f, 0x72, 0x74, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x22, 0x82, 0x01, 0x0a, 0x12, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x79,
	0x73, 0x4d, 0x65, 0x6e, 0x75, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x05,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x26, 0x0a, 0x09, 0x70, 0x61,
	0x67, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x50, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x26, 0x0a, 0x09, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x08, 0x73, 0x6f, 0x72, 0x74, 0x44, 0x61, 0x74, 0x61, 0x22, 0x67, 0x0a, 0x12, 0x46, 0x69,
	0x6e, 0x64, 0x53, 0x79, 0x73, 0x4d, 0x65, 0x6e, 0x75, 0x50, 0x61, 0x67, 0x65, 0x52, 0x73, 0x70,
	0x12, 0x29, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x79, 0x73, 0x4d, 0x65, 0x6e, 0x75, 0x52,
	0x73, 0x70, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x09, 0x70,
	0x61, 0x67, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09,
	0x2e, 0x50, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sys_menu_proto_rawDescOnce sync.Once
	file_sys_menu_proto_rawDescData = file_sys_menu_proto_rawDesc
)

func file_sys_menu_proto_rawDescGZIP() []byte {
	file_sys_menu_proto_rawDescOnce.Do(func() {
		file_sys_menu_proto_rawDescData = protoimpl.X.CompressGZIP(file_sys_menu_proto_rawDescData)
	})
	return file_sys_menu_proto_rawDescData
}

var file_sys_menu_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sys_menu_proto_goTypes = []interface{}{
	(*CreateSysMenuReq)(nil),   // 0: CreateSysMenuReq
	(*CreateSysMenuRsp)(nil),   // 1: CreateSysMenuRsp
	(*DeleteSysMenuReq)(nil),   // 2: DeleteSysMenuReq
	(*UpdateSysMenuReq)(nil),   // 3: UpdateSysMenuReq
	(*FindSysMenuByIdReq)(nil), // 4: FindSysMenuByIdReq
	(*FindSysMenuRsp)(nil),     // 5: FindSysMenuRsp
	(*FindSysMenuPageReq)(nil), // 6: FindSysMenuPageReq
	(*FindSysMenuPageRsp)(nil), // 7: FindSysMenuPageRsp
	(*Query)(nil),              // 8: Query
	(*PageData)(nil),           // 9: PageData
	(*SortData)(nil),           // 10: SortData
}
var file_sys_menu_proto_depIdxs = []int32{
	8,  // 0: FindSysMenuPageReq.query:type_name -> Query
	9,  // 1: FindSysMenuPageReq.page_data:type_name -> PageData
	10, // 2: FindSysMenuPageReq.sort_data:type_name -> SortData
	5,  // 3: FindSysMenuPageRsp.entries:type_name -> FindSysMenuRsp
	9,  // 4: FindSysMenuPageRsp.page_data:type_name -> PageData
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_sys_menu_proto_init() }
func file_sys_menu_proto_init() {
	if File_sys_menu_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_sys_menu_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSysMenuReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_menu_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSysMenuRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_menu_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSysMenuReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_menu_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSysMenuReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_menu_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindSysMenuByIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_menu_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindSysMenuRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_menu_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindSysMenuPageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_menu_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindSysMenuPageRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sys_menu_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sys_menu_proto_goTypes,
		DependencyIndexes: file_sys_menu_proto_depIdxs,
		MessageInfos:      file_sys_menu_proto_msgTypes,
	}.Build()
	File_sys_menu_proto = out.File
	file_sys_menu_proto_rawDesc = nil
	file_sys_menu_proto_goTypes = nil
	file_sys_menu_proto_depIdxs = nil
}
