# HTTP Server.
server:
  lang: zh-CN # "zh-CN", "zh-TW", "en"
  public_port: 6666 # 对外端口
  private_port: 6667 # 对内端口
  mcp_public_port: 6668 # MCP服务端口
  server_name: "public-center"
  mode: "debug" # gin的模式配置 debug, test, release
  dev: true # true,false;校验token等,开发模式的时候打开
  enable_event: false
  enable_job: true
  enable_grpc: false
  enable_mcp: false

# GRPC Server.
gserver:
  host: "0.0.0.0" # 当前服务
  public_port: 6669 # 当前服务
  max_msg_size: 1024 # 最大发送接收字节数,单位 m
  client_goods_host: "0.0.0.0" # goods服务的host
  client_goods_port: 18080 # goods服务的port

# Log.
log:
  log_file_dir: "/tmp/logs/"
  max_size: 512
  max_backups: 64
  max_age: 7
  log_level: "debug" #自定义日志； trace, debug, info,panic, fatal, error, warn
  log_out: 1 # 1:console, 2:file, 3:mq, 4:es, 5:zs, 6:otel; default is console

# Database.
db:
  db_type: "postgres"
  username: "root"
  password: "admin123"
  db_host: "127.0.0.1"
  db_port: 5432
  db_name: "ddddemo"
  charset: "utf8mb4"

  max_open_conn: 50 # 设置数据库连接池最大连接数
  max_idle_conn: 10 # 连接池最大允许的空闲连接数
  conn_max_lifetime: 500 # 设置连接可复用的最大时间
  log_mode: 4 # gorm错误级别; 1: Silent, 2:Error,3:Warn,4:Info
  slow_threshold: 10 # 慢查询
