// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/jett/gin-ddd/application/service/user"
	"github.com/jett/gin-ddd/interfaces"
)

import (
	_ "github.com/jett/gin-ddd/boot"
)

// Injectors from wire.go:

func NewApp() (*interfaces.Server, error) {
	server := interfaces.NewServer()
	return server, nil
}

// wire.go:

//go:generate wire
var providerSet = wire.NewSet(service.NewUserService, interfaces.NewServer)
